/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DBOperations.hr_DBAccess;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sachini
 */
public class hr_home extends javax.swing.JFrame {
    hr_DBAccess hr= new hr_DBAccess();
    List<List> listOfuserDetails = new ArrayList<List>();
          
    ArrayList<String> listOfStringData = new ArrayList<String>();
    ArrayList<Integer> listOfIntData = new ArrayList<Integer>();

    /**
     * Creates new form hr_home
     */
    public hr_home() {
        initComponents();
        tableLoad();
    }
    
    public void tableLoad()
    {
        tbl_search.setModel(DbUtils.resultSetToTableModel(hr.getAllUsers()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        index = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btn_action_login = new javax.swing.JButton();
        btn_action_register = new javax.swing.JButton();
        btn_action_veiwAll = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        maincomponentPane = new javax.swing.JDesktopPane();
        viewAll = new javax.swing.JPanel();
        txt_searchEmp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_search = new javax.swing.JTable();
        btn_searchEmp = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        register = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab_userDetails = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_a_address = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cal_dob = new com.toedter.calendar.JCalendar();
        radio_female = new javax.swing.JRadioButton();
        radio_male = new javax.swing.JRadioButton();
        btn_next = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tab_userDept = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cmb_dept = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cmb_supervisor = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        cmb_desgnation = new javax.swing.JComboBox();
        btn_next_2 = new javax.swing.JButton();
        tab_userAccounts = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_newUsername = new javax.swing.JTextField();
        txt_newPassword = new javax.swing.JPasswordField();
        txt_newConfirmPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        index.setPreferredSize(new java.awt.Dimension(700, 600));

        btn_action_login.setText("login");
        btn_action_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_action_loginActionPerformed(evt);
            }
        });

        btn_action_register.setText("Register");
        btn_action_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_action_registerActionPerformed(evt);
            }
        });

        btn_action_veiwAll.setText("Search Employee");
        btn_action_veiwAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_action_veiwAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_action_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_action_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_action_veiwAll, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btn_action_login, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_action_register, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_action_veiwAll, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setText("Human Resourses Mangement");

        maincomponentPane.setPreferredSize(new java.awt.Dimension(700, 622));
        maincomponentPane.setLayout(new java.awt.CardLayout());

        viewAll.setPreferredSize(new java.awt.Dimension(700, 600));
        viewAll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_searchEmp.setToolTipText("");
        txt_searchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchEmpActionPerformed(evt);
            }
        });
        viewAll.add(txt_searchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, -1));

        tbl_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Edit", "Delete"
            }
        ));
        tbl_search.setColumnSelectionAllowed(true);
        tbl_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_searchMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_search);
        tbl_search.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        viewAll.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 410, 170));

        btn_searchEmp.setText("Search");
        viewAll.add(btn_searchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        viewAll.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        btn_delete.setText("Delete");
        viewAll.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        maincomponentPane.add(viewAll, "card5");

        register.setPreferredSize(new java.awt.Dimension(600, 500));
        register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Register User");

        jLabel7.setText("Name");

        jLabel8.setText("Address");

        txt_a_address.setColumns(20);
        txt_a_address.setRows(5);
        jScrollPane1.setViewportView(txt_a_address);

        jLabel9.setText("E-mail");

        jLabel10.setText("Phone");

        jLabel12.setText("Date of Birth");

        radio_female.setText("Female");

        radio_male.setText("Male");
        radio_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_maleActionPerformed(evt);
            }
        });

        btn_next.setText("Next>>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        jLabel20.setText("Gender");

        javax.swing.GroupLayout tab_userDetailsLayout = new javax.swing.GroupLayout(tab_userDetails);
        tab_userDetails.setLayout(tab_userDetailsLayout);
        tab_userDetailsLayout.setHorizontalGroup(
            tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_userDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_userDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(tab_userDetailsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_userDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(radio_female)
                                .addGap(18, 18, 18)
                                .addComponent(radio_male)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tab_userDetailsLayout.createSequentialGroup()
                                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tab_userDetailsLayout.createSequentialGroup()
                                        .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cal_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane1))
                                            .addGroup(tab_userDetailsLayout.createSequentialGroup()
                                                .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 14, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_userDetailsLayout.createSequentialGroup()
                                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
            .addGroup(tab_userDetailsLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btn_next)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tab_userDetailsLayout.setVerticalGroup(
            tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_userDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_userDetailsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_userDetailsLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_female)
                    .addComponent(jLabel20)
                    .addComponent(radio_male))
                .addGap(18, 18, 18)
                .addGroup(tab_userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cal_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(btn_next)
                .addGap(0, 151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User Details", tab_userDetails);

        jLabel11.setText("Department");

        cmb_dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Supervisor");

        cmb_supervisor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Designation");

        cmb_desgnation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_next_2.setText("Next>>");
        btn_next_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_next_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_userDeptLayout = new javax.swing.GroupLayout(tab_userDept);
        tab_userDept.setLayout(tab_userDeptLayout);
        tab_userDeptLayout.setHorizontalGroup(
            tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_userDeptLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_userDeptLayout.createSequentialGroup()
                        .addGroup(tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_userDeptLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmb_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_userDeptLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmb_supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tab_userDeptLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_userDeptLayout.createSequentialGroup()
                                .addComponent(btn_next_2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmb_desgnation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(323, 323, 323))
        );
        tab_userDeptLayout.setVerticalGroup(
            tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_userDeptLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_dept)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(tab_userDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_desgnation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btn_next_2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User Department", tab_userDept);

        tab_userAccounts.setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel16.setText("Enter User Name");

        jLabel17.setText("Enter Password");

        jLabel18.setText("Confirm Password");

        txt_newConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newConfirmPasswordActionPerformed(evt);
            }
        });

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_userAccountsLayout = new javax.swing.GroupLayout(tab_userAccounts);
        tab_userAccounts.setLayout(tab_userAccountsLayout);
        tab_userAccountsLayout.setHorizontalGroup(
            tab_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_userAccountsLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(tab_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tab_userAccountsLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_userAccountsLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_newPassword))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_userAccountsLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(tab_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_newConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab_userAccountsLayout.setVerticalGroup(
            tab_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_userAccountsLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(tab_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_newUsername))
                .addGap(17, 17, 17)
                .addGroup(tab_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_newConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(539, 539, 539))
        );

        jTabbedPane1.addTab("User Accounts", tab_userAccounts);

        register.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 680));

        maincomponentPane.add(register, "card4");

        login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login.setPreferredSize(new java.awt.Dimension(700, 600));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User name:");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel2.setText("Password:");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        login.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 190, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Login");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 274, 38));

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        login.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 118, 37));

        jLabel4.setText("Not registerd ?");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, 40));

        btn_register.setText("Register");
        login.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 118, 37));
        login.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 192, 41));

        maincomponentPane.add(login, "card2");

        javax.swing.GroupLayout indexLayout = new javax.swing.GroupLayout(index);
        index.setLayout(indexLayout);
        indexLayout.setHorizontalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(indexLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maincomponentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        indexLayout.setVerticalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indexLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indexLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maincomponentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(indexLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(index, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        /**
         * check user login
         */        
            String username=txt_username.getText();
            String password=String.valueOf(txt_password.getPassword());
                      
            boolean status=hr.login(username,password);
            if(status){
                JOptionPane.showMessageDialog(null, "Sucessfully logged in","Successfull",  JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void radio_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_maleActionPerformed

    private void txt_newConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newConfirmPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /**
         * method to handle user registration
         */
        
        ArrayList<String> userList=new ArrayList<>();
        
        String fname=this.txt_fname.getText();
        String lname=this.txt_lname.getText();
        String address=this.txt_a_address.getText();
        String email=this.txt_email.getText();
        String phone=this.txt_phone.getText();
        //String dob=this.cal_dob.getDate().toString();
        String dob = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss")
            .format(cal_dob.getDate());
        
        String gender=null;
        if(radio_female.isSelected()) 
            gender="F";
        else if(radio_male.isSelected()) 
            gender="M";
        String department=String.valueOf(this.cmb_dept.getSelectedItem());
        String supevisor=String.valueOf(this.cmb_supervisor.getSelectedItem());
        String designation=String.valueOf(this.cmb_desgnation.getSelectedItem());
        
        //get department id
        String deptID=Integer.toString(hr.getDeptId(department));
        
        //getsupervisor id
        String superID=Integer.toString(hr.getsupID(supevisor));
        
        //add values to userList arrayList object
        userList.add(fname);
        userList.add(lname);
        userList.add(address);
        userList.add(dob);
        userList.add(email);
        userList.add(phone);
        userList.add(gender);
        userList.add(superID);
        userList.add(deptID);
        userList.add(designation);
        
        boolean status_1=hr.register(userList);
        
        
        //add values to useAccount ArraList object
        ArrayList<String> userAccount=new ArrayList<>();
        String username=this.txt_newUsername.getText();
        String password=String.valueOf(this.txt_newPassword.getPassword());
        userAccount.add(username);
        userAccount.add(password);
        
        boolean status_2=hr.addUserAccount(userAccount);
        if(status_1&&status_2){
            JOptionPane.showMessageDialog(null, "Sucessfully Registerd","Successfull",  JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        //error message
        }                           
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_action_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_action_loginActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        menuPanel.setVisible(true);
        register.setVisible(false);
        login.setVisible(true);
        viewAll.setVisible(false);
    }//GEN-LAST:event_btn_action_loginActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        this.setVisible(true);
        this.index.setVisible(true);
        this.login.setVisible(false);
        this.register.setVisible(false);
        viewAll.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void btn_action_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_action_registerActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        menuPanel.setVisible(true);
        register.setVisible(true);
        login.setVisible(false);
        viewAll.setVisible(false);
    }//GEN-LAST:event_btn_action_registerActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_next_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_next_2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btn_next_2ActionPerformed

    private void btn_action_veiwAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_action_veiwAllActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        menuPanel.setVisible(true);
        register.setVisible(false);
        login.setVisible(false);
        viewAll.setVisible(true);
    }//GEN-LAST:event_btn_action_veiwAllActionPerformed

    private void txt_searchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchEmpActionPerformed

    private void tbl_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_searchMouseClicked
        // TODO add your handling code here:
          int r=tbl_search.getSelectedRow();
          
          int userId=(Integer)(tbl_search.getValueAt(r, 0));
          String fname=(String) tbl_search.getValueAt(r, 1);
          String lname=(String) tbl_search.getValueAt(r, 2);        
          String email=(String) tbl_search.getValueAt(r, 3);
          String phone=(String) tbl_search.getValueAt(r, 4);
          String address=(String) tbl_search.getValueAt(r, 5);
          String gender=(String) tbl_search.getValueAt(r, 6);
          String dob=(String) tbl_search.getValueAt(r, 7);
          int dept=(Integer)(tbl_search.getValueAt(r, 8));
          int sup=(Integer) (tbl_search.getValueAt(r, 9));
          String designation=(String) tbl_search.getValueAt(r, 10);
          
          List<List> listOfuserDetails = new ArrayList<List>();
          
          ArrayList<String> listOfStringData = new ArrayList<String>();
          ArrayList<Integer> listOfIntData = new ArrayList<Integer>();
          
          listOfStringData.add(fname);
          listOfStringData.add(lname);
          listOfStringData.add(email);
          listOfStringData.add(phone);
          listOfStringData.add(address);
          listOfStringData.add(gender);
          listOfStringData.add(dob);
          listOfStringData.add(designation);
          
          listOfIntData.add(userId);
          listOfIntData.add(dept);
          listOfIntData.add(sup);
          
          listOfuserDetails.add(listOfStringData);
          listOfuserDetails.add(listOfIntData);          
      
    }//GEN-LAST:event_tbl_searchMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null, "Do you want to update?");
        
        if(x==0)
        {
            if(hr.updateUser(listOfuserDetails))
            {
                JOptionPane.showMessageDialog(null,"Successfuly updated","Alert",JOptionPane.INFORMATION_MESSAGE);
                tableLoad();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error ","Alert",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hr_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hr_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hr_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hr_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hr_home().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_action_login;
    private javax.swing.JButton btn_action_register;
    private javax.swing.JButton btn_action_veiwAll;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_next_2;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_searchEmp;
    private javax.swing.JButton btn_update;
    private com.toedter.calendar.JCalendar cal_dob;
    private javax.swing.JComboBox cmb_dept;
    private javax.swing.JComboBox cmb_desgnation;
    private javax.swing.JComboBox cmb_supervisor;
    private javax.swing.JPanel index;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel login;
    private javax.swing.JDesktopPane maincomponentPane;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JPanel register;
    private javax.swing.JPanel tab_userAccounts;
    private javax.swing.JPanel tab_userDept;
    private javax.swing.JPanel tab_userDetails;
    private javax.swing.JTable tbl_search;
    private javax.swing.JTextArea txt_a_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JPasswordField txt_newConfirmPassword;
    private javax.swing.JPasswordField txt_newPassword;
    private javax.swing.JTextField txt_newUsername;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_searchEmp;
    private javax.swing.JTextField txt_username;
    private javax.swing.JPanel viewAll;
    // End of variables declaration//GEN-END:variables
}
